version: '3'

services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  api:
    image: api:latest
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq

  worker:
    image: worker:latest
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
