version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  api:
    image: api:latest
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - redis

  worker:
    image: worker:latest
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
      - redis